services:
  - type: web
    name: dhaman-vastra
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 16
    headers:
      - path: /firebase-messaging-sw.js
        headers:
          - key: Cache-Control
            value: no-cache
          - key: Service-Worker-Allowed
            value: /
          - key: Content-Type
            value: application/javascript 