services:
  - type: web
    name: dhaman-vastra
    rootDir: Smart-Server
    buildCommand: |
      cd Smart-Server
      npm install
      npm run build
      cp -f public/firebase-messaging-sw.js build/ 2>/dev/null || true
      cp public/_redirects build/_redirects 2>/dev/null || true
    startCommand: |
      cd Smart-Server
      npx serve -s build
    envVars:
      - key: NODE_VERSION
        value: 16
    headers:
      - path: /firebase-messaging-sw.js
        headers:
          - key: Cache-Control
            value: no-cache
          - key: Service-Worker-Allowed
            value: /
          - key: Content-Type
            value: application/javascript 